[project]
name = "bayesian-email-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "statsmodels>=0.14.4",
    "streamlit>=1.44.1",
]
